export interface Match {
  id: string;
  teamA: string;
  teamB: string;
  sport: "Cricket";
  scoreA: string;
  scoreB: string;
  overs: string;
  status: string;
  matchContext: string;   // e.g. "MI need 47 in 34 balls" or "CSK won by 5 wkts"
  venue: string;
  recentEvents: string[];
  teamAMomentum: number;
  teamBMomentum: number;
  prediction: {
    question: string;
    yesVotes: number;
    noVotes: number;
  };
}

// Fallback IPL 2026 mock data used when no CricAPI key is set or no live matches found
export const MOCK_MATCHES: Match[] = [
  {
    id: "ipl-mi-csk",
    teamA: "Mumbai Indians",
    teamB: "Chennai Super Kings",
    sport: "Cricket",
    scoreA: "156/4 (15.3 ov)",
    scoreB: "Yet to bat",
    overs: "Over 15.3 / 20",
    status: "LIVE",
    matchContext: "CSK need 157 runs to win off 27 balls",
    venue: "Wankhede Stadium, Mumbai",
    recentEvents: [
      "CSK need 157 runs to win off 27 balls",
      "SIX by Rohit Sharma over long-on off Jadeja",
      "FOUR by Suryakumar Yadav through extra cover",
      "Wicket: Tilak Varma caught at deep mid-wicket",
    ],
    teamAMomentum: 58,
    teamBMomentum: 42,
    prediction: {
      question: "Will MI post 180+ in this innings?",
      yesVotes: 512,
      noVotes: 288,
    },
  },
  {
    id: "ipl-rcb-kkr",
    teamA: "Royal Challengers Bengaluru",
    teamB: "Kolkata Knight Riders",
    sport: "Cricket",
    scoreA: "192/5 (20 ov)",
    scoreB: "143/7 (16.4 ov)",
    overs: "KKR need 50 off 20 balls",
    status: "LIVE",
    matchContext: "KKR need 50 runs off 20 balls",
    venue: "M. Chinnaswamy Stadium, Bengaluru",
    recentEvents: [
      "KKR need 50 runs off 20 balls",
      "SIX by Rinku Singh over square leg off Siraj",
      "FOUR by Andre Russell through covers",
      "Wicket: Sunil Narine stumped off Chahal",
    ],
    teamAMomentum: 71,
    teamBMomentum: 29,
    prediction: {
      question: "Will KKR win this chase?",
      yesVotes: 190,
      noVotes: 610,
    },
  },
  {
    id: "ipl-srh-rr",
    teamA: "Sunrisers Hyderabad",
    teamB: "Rajasthan Royals",
    sport: "Cricket",
    scoreA: "87/2 (9.1 ov)",
    scoreB: "Yet to bat",
    overs: "Over 9.1 / 20",
    status: "LIVE",
    matchContext: "SRH on track for 185+ at current run rate",
    venue: "Rajiv Gandhi International Stadium, Hyderabad",
    recentEvents: [
      "SRH on track for 185+ at current run rate",
      "FOUR by Travis Head through point off Boult",
      "SIX by Abhishek Sharma over mid-wicket",
      "Wicket: Heinrich Klaasen caught at slip off Chahal",
    ],
    teamAMomentum: 63,
    teamBMomentum: 37,
    prediction: {
      question: "Will SRH reach 200+ today?",
      yesVotes: 445,
      noVotes: 255,
    },
  },
  {
    id: "ipl-gt-lsg",
    teamA: "Gujarat Titans",
    teamB: "Lucknow Super Giants",
    sport: "Cricket",
    scoreA: "176/6 (20 ov)",
    scoreB: "178/4 (19.2 ov)",
    overs: "Over 19.2 / 20",
    status: "Result",
    matchContext: "Lucknow Super Giants won by 6 wickets",
    venue: "Narendra Modi Stadium, Ahmedabad",
    recentEvents: [
      "Lucknow Super Giants won by 6 wickets",
      "SIX by KL Rahul off last ball to seal victory",
      "FOUR by Quinton de Kock through cover",
      "Wicket: Shubman Gill bowled by Mohsin Khan",
    ],
    teamAMomentum: 38,
    teamBMomentum: 62,
    prediction: {
      question: "Will LSG complete the chase without losing more wickets?",
      yesVotes: 620,
      noVotes: 180,
    },
  },
  // ─── Upcoming fixtures ──────────────────────────────────────────────────────
  {
    id: "ipl-pbks-dc",
    teamA: "Punjab Kings",
    teamB: "Delhi Capitals",
    sport: "Cricket",
    scoreA: "Yet to bat",
    scoreB: "Yet to bat",
    overs: "Tomorrow · 19 May 2026, 7:30 PM IST",
    status: "19 May, 7:30 PM",
    matchContext: "",
    venue: "PCA Stadium, Mullanpur",
    recentEvents: ["Punjab Kings vs Delhi Capitals — Tomorrow"],
    teamAMomentum: 50,
    teamBMomentum: 50,
    prediction: {
      question: "Will Punjab Kings win at home against Delhi?",
      yesVotes: 340,
      noVotes: 260,
    },
  },
  {
    id: "ipl-lsg-gt2",
    teamA: "Lucknow Super Giants",
    teamB: "Gujarat Titans",
    sport: "Cricket",
    scoreA: "Yet to bat",
    scoreB: "Yet to bat",
    overs: "20 May 2026, 3:30 PM IST",
    status: "20 May, 3:30 PM",
    matchContext: "",
    venue: "BRSABV Ekana Stadium, Lucknow",
    recentEvents: ["Lucknow Super Giants vs Gujarat Titans — 20 May"],
    teamAMomentum: 50,
    teamBMomentum: 50,
    prediction: {
      question: "Will Lucknow win the home fixture against Gujarat?",
      yesVotes: 390,
      noVotes: 210,
    },
  },
];

export function getMockMatch(id: string): Match | undefined {
  return MOCK_MATCHES.find((m) => m.id === id);
}

// ─── IPL 2026 — Completed match results (mock fallback) ──────────────────────

export const MOCK_PAST_MATCHES: Match[] = [
  {
    id: "ipl26-1",
    teamA: "Kolkata Knight Riders",
    teamB: "Royal Challengers Bengaluru",
    sport: "Cricket",
    scoreA: "201/4 (20 ov)",
    scoreB: "195/7 (20 ov)",
    overs: "Completed · 7 May 2026",
    status: "Result",
    matchContext: "Kolkata Knight Riders won by 6 runs",
    venue: "Eden Gardens, Kolkata",
    recentEvents: [
      "Kolkata Knight Riders won by 6 runs",
      "Sunil Narine smashed 71 off 32 balls to anchor KKR innings",
      "Faf du Plessis hit 58 off 38 for RCB in a valiant chase",
      "Andre Russell took 3/24 to restrict RCB in the final overs",
      "Last over thriller — RCB needed 12 off 6, got only 6",
      "Phil Salt scored 48 off 28 at the top for KKR",
    ],
    teamAMomentum: 55,
    teamBMomentum: 45,
    prediction: {
      question: "Will KKR defend their total successfully?",
      yesVotes: 540,
      noVotes: 260,
    },
  },
  {
    id: "ipl26-2",
    teamA: "Chennai Super Kings",
    teamB: "Mumbai Indians",
    sport: "Cricket",
    scoreA: "168/8 (20 ov)",
    scoreB: "169/3 (18.4 ov)",
    overs: "Completed · 5 May 2026",
    status: "Result",
    matchContext: "Mumbai Indians won by 7 wickets",
    venue: "MA Chidambaram Stadium, Chennai",
    recentEvents: [
      "Mumbai Indians won by 7 wickets",
      "Rohit Sharma scored 72 off 48 to lead comfortable chase",
      "Ruturaj Gaikwad top-scored for CSK with 54 off 41",
      "Jasprit Bumrah took 2/18 with masterclass in death bowling",
      "Suryakumar Yadav hit 43* off 22 to finish the game",
      "CSK lost 4 wickets in final 4 overs to limit total to 168",
    ],
    teamAMomentum: 42,
    teamBMomentum: 58,
    prediction: {
      question: "Will Mumbai Indians win the El Clasico?",
      yesVotes: 480,
      noVotes: 420,
    },
  },
  {
    id: "ipl26-3",
    teamA: "Rajasthan Royals",
    teamB: "Sunrisers Hyderabad",
    sport: "Cricket",
    scoreA: "214/3 (20 ov)",
    scoreB: "198/6 (20 ov)",
    overs: "Completed · 3 May 2026",
    status: "Result",
    matchContext: "Rajasthan Royals won by 16 runs",
    venue: "Sawai Mansingh Stadium, Jaipur",
    recentEvents: [
      "Rajasthan Royals won by 16 runs",
      "Jos Buttler blazed 95 off 55 to power RR to 214",
      "Yashasvi Jaiswal contributed 68 off 42 at the top",
      "Travis Head hit 78 off 44 in a spirited SRH chase",
      "Yuzvendra Chahal took 3/26 to derail SRH's chase",
      "Abhishek Sharma dismissed early for just 8 by Avesh Khan",
    ],
    teamAMomentum: 60,
    teamBMomentum: 40,
    prediction: {
      question: "Will RR post 200+ today?",
      yesVotes: 610,
      noVotes: 190,
    },
  },
  {
    id: "ipl26-4",
    teamA: "Punjab Kings",
    teamB: "Delhi Capitals",
    sport: "Cricket",
    scoreA: "152/9 (20 ov)",
    scoreB: "153/5 (19.1 ov)",
    overs: "Completed · 1 May 2026",
    status: "Result",
    matchContext: "Delhi Capitals won by 5 wickets",
    venue: "PCA Stadium, Mullanpur",
    recentEvents: [
      "Delhi Capitals won by 5 wickets",
      "Arshdeep Singh took 3/22 but Delhi crossed the line",
      "Axar Patel hit 41* off 25 in a nervy finish for DC",
      "Shashank Singh top-scored for PBKS with 42 off 31",
      "Kagiso Rabada bowled 4 overs for just 22 runs",
      "Jake Fraser-McGurk smashed 36 off 18 to set up DC win",
    ],
    teamAMomentum: 40,
    teamBMomentum: 60,
    prediction: {
      question: "Will Punjab Kings defend 152 at home?",
      yesVotes: 310,
      noVotes: 490,
    },
  },
  {
    id: "ipl26-5",
    teamA: "Lucknow Super Giants",
    teamB: "Gujarat Titans",
    sport: "Cricket",
    scoreA: "188/5 (20 ov)",
    scoreB: "140/10 (18.3 ov)",
    overs: "Completed · 29 Apr 2026",
    status: "Result",
    matchContext: "Lucknow Super Giants won by 48 runs",
    venue: "BRSABV Ekana Stadium, Lucknow",
    recentEvents: [
      "Lucknow Super Giants won by 48 runs",
      "KL Rahul played anchor innings of 76 off 52 for LSG",
      "Nicholas Pooran smashed 44 off 21 with 4 sixes for LSG",
      "Mohit Sharma took 4/28 to rip apart Gujarat Titans batting",
      "Shubman Gill scored 38 before falling to Krunal Pandya",
      "Gujarat Titans lost their last 6 wickets for just 42 runs",
    ],
    teamAMomentum: 68,
    teamBMomentum: 32,
    prediction: {
      question: "Will LSG post 180+ batting first?",
      yesVotes: 490,
      noVotes: 310,
    },
  },
  {
    id: "ipl26-6",
    teamA: "Mumbai Indians",
    teamB: "Rajasthan Royals",
    sport: "Cricket",
    scoreA: "177/6 (20 ov)",
    scoreB: "178/2 (17.3 ov)",
    overs: "Completed · 27 Apr 2026",
    status: "Result",
    matchContext: "Rajasthan Royals won by 8 wickets",
    venue: "Wankhede Stadium, Mumbai",
    recentEvents: [
      "Rajasthan Royals won by 8 wickets",
      "Sanju Samson smashed unbeaten 89 off 48 in clinical chase",
      "Yashasvi Jaiswal opened with blistering 71 off 40",
      "Suryakumar Yadav top-scored for MI with 62 off 38",
      "Trent Boult took 2/22 with two crucial early wickets",
      "MI lost momentum in overs 15–18, managing just 28 runs",
    ],
    teamAMomentum: 38,
    teamBMomentum: 62,
    prediction: {
      question: "Will MI win the home game against RR?",
      yesVotes: 520,
      noVotes: 280,
    },
  },
  {
    id: "ipl26-7",
    teamA: "Sunrisers Hyderabad",
    teamB: "Kolkata Knight Riders",
    sport: "Cricket",
    scoreA: "223/4 (20 ov)",
    scoreB: "209/7 (20 ov)",
    overs: "Completed · 25 Apr 2026",
    status: "Result",
    matchContext: "Sunrisers Hyderabad won by 14 runs",
    venue: "Rajiv Gandhi International Stadium, Hyderabad",
    recentEvents: [
      "Sunrisers Hyderabad won by 14 runs",
      "Travis Head scored 102 off 55 — his third IPL century",
      "Heinrich Klaasen blasted 67 off 35 in powerhouse partnership",
      "Rinku Singh fought with 58 off 34 but KKR fell short",
      "Pat Cummins took 3/32 to restrict KKR in the final overs",
      "Sunil Narine bowled out for 4 — rare failure for him",
    ],
    teamAMomentum: 58,
    teamBMomentum: 42,
    prediction: {
      question: "Will SRH post 200+ at their fortress?",
      yesVotes: 680,
      noVotes: 120,
    },
  },
  {
    id: "ipl26-8",
    teamA: "Royal Challengers Bengaluru",
    teamB: "Chennai Super Kings",
    sport: "Cricket",
    scoreA: "163/7 (20 ov)",
    scoreB: "164/4 (19.4 ov)",
    overs: "Completed · 23 Apr 2026",
    status: "Result",
    matchContext: "Chennai Super Kings won by 6 wickets",
    venue: "M. Chinnaswamy Stadium, Bengaluru",
    recentEvents: [
      "Chennai Super Kings won by 6 wickets",
      "MS Dhoni finished the match with a six in the 20th over",
      "Virat Kohli scored 71 off 49 for RCB in a losing cause",
      "Ravindra Jadeja took 2/22 and hit 28* to seal the win",
      "Mohammed Siraj took 3/27 to restrict CSK to a tough chase",
      "Ruturaj Gaikwad led the chase with composed 55 off 41",
    ],
    teamAMomentum: 44,
    teamBMomentum: 56,
    prediction: {
      question: "Will RCB defend 163 at their home ground?",
      yesVotes: 340,
      noVotes: 460,
    },
  },
];
