"use client";

import { useState, useEffect } from "react";
import type { Match } from "@/lib/matches";
import type { MatchReport } from "@/app/api/ai/report/route";

async function shareReport(report: MatchReport, match: Match) {
  const text = [
    `🏏 ${match.teamA} vs ${match.teamB}`,
    `📰 ${report.headline}`,
    ``,
    `🏆 Man of the Match: ${report.manOfMatch}`,
    `${report.manOfMatchReason}`,
    ``,
    `Key Moments:`,
    ...report.keyMoments.map((m, i) => `${i + 1}. ${m}`),
    ``,
    `Generated by CricGenie AI · cricgenie.app`,
  ].join("\n");

  if (navigator.share) {
    await navigator.share({ title: report.headline, text });
  } else {
    await navigator.clipboard.writeText(text);
  }
}

function StarRating({ rating }: { rating: number }) {
  const full = Math.floor(rating / 2);
  const half = rating % 2 >= 1;
  return (
    <div className="flex items-center gap-0.5">
      {Array.from({ length: 5 }).map((_, i) => (
        <span
          key={i}
          className={`text-xs ${
            i < full
              ? "text-yellow-400"
              : i === full && half
              ? "text-yellow-400/50"
              : "text-zinc-700"
          }`}
        >
          ★
        </span>
      ))}
      <span className="text-xs text-zinc-500 ml-1">{rating.toFixed(1)}</span>
    </div>
  );
}

function ShareButton({ report, match }: { report: MatchReport; match: Match }) {
  const [copied, setCopied] = useState(false);
  const handleShare = async () => {
    await shareReport(report, match);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <button
      onClick={handleShare}
      className="text-xs text-amber-400 border border-amber-500/30 bg-amber-500/10 hover:bg-amber-500/20 px-3 py-1.5 rounded-lg transition-all"
    >
      {copied ? "✓ Copied!" : "Share Report"}
    </button>
  );
}

export default function PostMatchReport({
  match,
  autoGenerate = false,
}: {
  match: Match;
  autoGenerate?: boolean;
}) {
  const [report, setReport] = useState<MatchReport | null>(null);
  const [loading, setLoading] = useState(false);

  // Auto-generate on mount when viewing a completed match
  useEffect(() => {
    if (autoGenerate) generate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoGenerate]);

  const generate = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/ai/report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ match }),
      });
      const data = await res.json();
      setReport(data);
    } catch {
      setReport(null);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-5 mb-4">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-full bg-amber-500/20 border border-amber-500/30 flex items-center justify-center flex-shrink-0">
            <span className="text-amber-400 text-xs font-bold">AI</span>
          </div>
          <div>
            <p className="text-sm font-semibold text-white leading-none mb-0.5">
              AI Match Report
            </p>
            <p className="text-xs text-amber-400/70">Powered by Google Gemini</p>
          </div>
        </div>
        {report && (
          <div className="flex gap-2">
            <ShareButton report={report} match={match} />
            <button
              onClick={generate}
              disabled={loading}
              className="text-xs text-zinc-500 hover:text-zinc-300 border border-zinc-700 px-3 py-1.5 rounded-lg transition-all"
            >
              Regenerate
            </button>
          </div>
        )}
      </div>

      {/* Empty state */}
      {!report && !loading && (
        <div className="text-center py-6">
          <p className="text-zinc-500 text-sm mb-1">
            Get a full AI-written match analysis
          </p>
          <p className="text-zinc-600 text-xs mb-5">
            Headline · narrative · key moments · player ratings
          </p>
          <button
            onClick={generate}
            className="bg-amber-500/20 border border-amber-500/40 text-amber-300 hover:bg-amber-500/30 px-6 py-2.5 rounded-xl text-sm font-semibold transition-all"
          >
            Generate Match Report
          </button>
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div className="text-center py-8">
          <div className="flex justify-center gap-1.5 mb-3">
            <span className="w-2 h-2 bg-amber-400 rounded-full animate-bounce [animation-delay:-0.3s]" />
            <span className="w-2 h-2 bg-amber-400 rounded-full animate-bounce [animation-delay:-0.15s]" />
            <span className="w-2 h-2 bg-amber-400 rounded-full animate-bounce" />
          </div>
          <p className="text-zinc-500 text-xs">
            Gemini is writing the match report…
          </p>
        </div>
      )}

      {/* Report */}
      {report && !loading && (
        <div className="space-y-5">
          {/* Headline */}
          <h2 className="text-lg font-black text-white leading-snug">
            {report.headline}
          </h2>

          {/* Narrative */}
          <div>
            {report.summary.split("\n\n").map((para, i) => (
              <p key={i} className="text-zinc-300 text-sm leading-relaxed mb-2 last:mb-0">
                {para}
              </p>
            ))}
          </div>

          {/* Key moments */}
          <div className="bg-zinc-800 rounded-xl p-4">
            <p className="text-xs text-zinc-500 uppercase tracking-widest font-semibold mb-3">
              Key Moments
            </p>
            <div className="space-y-2">
              {report.keyMoments.map((moment, i) => (
                <div key={i} className="flex items-start gap-2.5">
                  <span className="text-amber-400 text-xs font-bold mt-0.5 flex-shrink-0">
                    {i + 1}.
                  </span>
                  <span className="text-zinc-300 text-xs leading-relaxed">
                    {moment}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Man of the Match */}
          <div className="bg-amber-500/10 border border-amber-500/25 rounded-xl p-4 flex items-center gap-3">
            <span className="text-3xl">🏆</span>
            <div>
              <p className="text-xs text-amber-400/70 uppercase tracking-widest font-semibold mb-0.5">
                Man of the Match
              </p>
              <p className="text-base font-black text-amber-300">
                {report.manOfMatch}
              </p>
              <p className="text-xs text-zinc-400 mt-0.5">
                {report.manOfMatchReason}
              </p>
            </div>
          </div>

          {/* Player ratings */}
          <div>
            <p className="text-xs text-zinc-500 uppercase tracking-widest font-semibold mb-3">
              Player Ratings
            </p>
            <div className="space-y-3">
              {report.playerRatings.map((p, i) => (
                <div
                  key={i}
                  className="flex items-center gap-3 bg-zinc-800 rounded-xl px-4 py-3"
                >
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-semibold text-white truncate">
                      {p.name}
                    </p>
                    <p className="text-xs text-zinc-500 truncate">{p.note}</p>
                  </div>
                  <div className="flex-shrink-0 text-right">
                    <StarRating rating={p.rating} />
                    <p className="text-xs text-zinc-600 mt-0.5">{p.team}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {report.source === "gemini" && (
            <p className="text-xs text-zinc-600 text-center">
              Generated by Google Gemini 1.5 Flash
            </p>
          )}
        </div>
      )}
    </div>
  );
}
